### ISSUE TITLE
Ensure repo is configured properly

### ISSUE THREAD

**Issue by philschatz** [openstax/highlighter#1]
https://github.com/openstax/napkin-notes/blob/master/checklists.md#new-github-repo

Or, discuss having this be part of an existing repo

**Comment by TomWoodward** [comment]
i did everything except the travis configs, thinking about omitting that and adding jenkinsfiles instead

**Comment by TomWoodward** [comment]
@philschatz is there anything left to do on this?

**Comment by philschatz** [comment]
Can you add a `README.md` with instructions for building/testing locally? Also, should we enable greenkeeper.io on this to get auto-tested package updates?

**Comment by philschatz** [comment]
Also, want to submit a PR to update the checklist so there's a Travis block and a Jenkins block for future repos?

**Comment by TomWoodward** [comment]
@philschatz i think we're good here, i think greenkeeper is enabled although it hasn't made the pr that it said it would yet
